vuex-orm/vuex-orm-next

src/model/Model.ts
src/support/Utils.ts
test/unit/model/Model.spec.ts

Throw when user accesses the `model.$store` function without having store injected. This happens when user tries to do `new User().$store` kinda thing. Users should be directed to use `repository.make()` method instead.

feat: throw error when accessing `model.$store` without store being injected

---

src/query/Options.ts
src/query/Query.ts
src/repository/Repository.ts
src/support/Utils.ts
test/feature/repository/retrieves_order_by.spec.ts

Similar to the current feature, allow handlers to be passed into the field param for the `orderBy` modifier.

feat: `orderBy` supports passing a handler as a field param

---

src/model/Model.ts

This PR resolves #10 where a fortuitous side-effect is caused by model's exposing the `_store` property.

fix(model): prevent `_store` from becoming a cyclic object value.

---

src/interpreter/Interpreter.ts
src/model/attributes/relations/BelongsTo.ts
src/model/attributes/relations/HasMany.ts
src/model/attributes/relations/HasOne.ts
src/model/attributes/relations/Relation.ts
src/schema/Schema.ts

This PR refactors the way we attach foreign key to the relationship.
Previously, we were attaching missing foreign keys after the normalization by looping through whole normalized data. With this new approach, we'll do that inside `IdAttribute` option of Normalizr.
It makes things a bit simpler since now `Relation.attach` method. But more importantly, this makes upcoming UID attribute implementation easier. Because we can generate both UID and foreign key at the same process (inside `IdAttribute` option). This makes users to define `UID` type at the `foreign key` and still get the right result.

refactor: the way to attach foreign key to the relationships

---

package.json
rollup.config.js
src/index.cjs.ts
src/index.ts
src/model/Model.ts
src/model/ModelConstructor.ts
src/model/attributes/types/Uid.ts
src/model/decorators/attributes/types/Uid.ts
src/plugin/Plugin.ts
src/query/Query.ts
src/repository/Repository.ts
src/schema/Schema.ts
test/Helpers.ts
test/feature/relations/types/belongs_to_insert_uid.spec.ts
test/feature/relations/types/has_many_insert_uid.spec.ts
test/feature/relations/types/has_one_insert_uid.spec.ts
test/feature/repository/inserts_fresh_uid.spec.ts
test/feature/repository/inserts_insert_uid.spec.ts
test/setup.ts
test/unit/model/Model_Attrs_UID.spec.ts
yarn.lock

Add UID attribute.
I had to modify few parts.
Previously, we were simply instantiating model when registering it to the database, or using in repository. Instead, now model accepts `null` as the constructor argument. When `null` is passed, all field value generation will be skipped.
Usually, users should never pass `null`. But pre-registered models don't require fields. It's better for performance, but also it avoids calling uuid multiple times making it hard to mock inside the test. Maybe we could add helper static function to model to create a new model instance without field, because we might for get to pass null in the future when creating new attributes.
This is not new to this PR, but seems like we have to clear the model field registries on each test if we want to declare the same …

feat: add uid attribute

---

src/model/Model.ts
src/query/Query.ts
src/schema/Schema.ts
test/feature/repository/deletes_destroy_composite_key.spec.ts
test/feature/repository/inserts_fresh_composite_key.spec.ts
test/feature/repository/inserts_insert_composite_key.spec.ts
test/feature/repository/updates_update_composite_key.spec.ts
test/unit/model/Model_Keys.spec.ts

This PR adds composite key support.
The composite key works as same as current Vuex ORM. It will generate index id looks as stringified array of ids (e.g. `'[1,2]'`).
Currently `destroy` method will throw immediately if the model has composite key because it doesn't make sense yet. Not sure if we would want to support composite key on such methods since users could do `repo.where('idA', 1).where('idB', 2).delete()`.
At least for now, I think we can stay not supporting composite key in the methods that requires a single primary key to be passed in. We could come up with better idea in the future.

feat: support composite key

---

docs/guide/repository/inserting-data.md

Add repository inserting data page.

docs: add repository inserting data page

---

docs/guide/relationships/getting-started.md
docs/guide/repository/getting-started.md
src/model/Model.ts
src/query/Query.ts
test/feature/relations/lazy_loads/lazy_eager_load.spec.ts

This PR adds lazy relationship loading feature. [See docs](https://github.com/vuex-orm/vuex-orm-next/pull/44/files#diff-c27b4e8b9ce931dd4d958fb121c13e5b4564bb062a2c69eed263b6c473e1f2d0) for the API.

feat: add lazy relationship loading feature

---

docs/guide/relationships/getting-started.md

Update getting-started.md : Typo on Relation

---

src/model/Model.ts
src/query/Query.ts
src/repository/Repository.ts
src/schema/Schema.ts
test/feature/repository/inserts_add.spec.ts
test/feature/repository/inserts_add_composite_key.spec.ts
test/feature/repository/inserts_add_uid.spec.ts
test/feature/repository/inserts_replace.spec.ts
test/feature/repository/inserts_replace_composite_key.spec.ts
test/feature/repository/inserts_replace_uid.spec.ts

This PR implements the repository's `add` and `replace` methods that happen to be missing but are documented.

fix(repository): implement missing `add` & `replace` methods

---

src/connection/Connection.ts
src/database/Database.ts
src/interpreter/Interpreter.ts
src/model/Model.ts
src/query/Query.ts
src/repository/Repository.ts
src/store/Store.ts
src/types/vuex.ts
test/unit/model/Model.spec.ts
test/unit/repository/Repository.spec.ts

This is from a discussion with @kiaking and @cuebit on the Slack.
This adds support for multiple namespaces.
Repositories or Models can be registered and accessed under multiple namespaces via `store.$repo(Model, 'namepace')`.
Some classes now retain the database rather than the store.

feat: Add support for multiple databases

---

src/schema/Schema.ts
test/regression/nested_relations.spec.ts
test/regression/normalizing_nested_relations_missing_parent_model.spec.ts

A model with more than 2 related models related to the same model was causing a normalization error. It was due to the Schema class was caching the first created schema with its key.
For example, the first relation creates a schema and say its name is `proposal_settings`. Now the parent of this model is `proposal_templates`, because it's defined first in Opportunity model.
Next, if the `proposals` model also depends on `proposal_settings`, but because the schema for `proposal_settings` is already created by `proposal_templates`, it uses the same `proposal_settings` schema. Now we have problem because the parent model this time should be `proposals` but it's using the previous `proposal_templates`. 
We've fixed this by caching the schema with `model` AND `parent` entity name. So only when …

fix: normalization error on nested relationship

---

src/query/Query.ts
src/repository/Repository.ts
test/feature/repository/inserts_new.spec.ts

closes #57 
Similar to `make()`, but with persistence, this PR adds the `new()` method to the `Repository` and `Query` APIs to create and persist a data entry with default-only values.

feat: add the `new` method to create and persist entry with default values (#57)

---

rollup.config.js
src/connection/Connection.ts
src/data/Data.ts
src/interpreter/Interpreter.ts
src/model/Model.ts
src/modules/Mutations.ts
src/query/Query.ts
src/repository/Repository.ts
src/schema/Schema.ts
test/feature/relations/has_many_retrieve.spec.ts
test/feature/relations/has_many_save.spec.ts
test/feature/relations/nested/nested_revive.spec.ts
test/feature/repository/retrieves_revive.spec.ts
test/feature/repository/save.spec.ts
test/unit/model/Model_Sanitize.spec.ts

ref #60 
This PR adds 2 new method to the repository. `save` and `revive`.
The `save` method will insert a given data, or update it if it already exists in the store. It will also normalize any relationships as well.
```js
userRepo.save({ id: 1, name: 'John Doe' })
```
The save method will return something we call `schema`, which is the original data passed into the `save` method, but with special `__id` key attached.
```js
const data = {
id: 1,
posts: [
{ id: 2, userId: 1 },
{ id: 1, userId: 1 }
]
}
const schema = userRepo.save(data)
/*
{
__id: '1', // <- Attached!
id: 1,
posts: [
{ __id: '2', id: 2, userId: 1 }, // <- Attached!
{ __id: '1', id: 1, userId: 1 }  // <- Attached!
]
}
*/
```
We may now pass this `schema` to the new `revive` method to retrieve the models.
```js
const user = …
```

feat: add `save` and `revive` method

---

src/model/Model.ts
test/feature/model/deletes_delete.spec.ts
test/feature/model/deletes_delete_composite_key.spec.ts
test/feature/relations/has_many_save.spec.ts

resolves #76 
Technically, this is not considered a breaking change (despite changing the shape of the method) since all API's were recently refactored to a non-async workflow.
In addition, tests are revised to reflect synchronous behavior.

fix(model): delete method should be synchronous (#76)

---

src/model/attributes/relations/BelongsTo.ts
src/model/attributes/relations/HasMany.ts
src/model/attributes/relations/HasOne.ts

Context: https://github.com/vuex-orm/vuex-orm-next/pull/91/files/5c1a11779811408f0caf6dd30bb9b28245e90792#r744380891
Removing `as any` from relation `addEagerConstraints` method as it is no longer required because trying to type hint the `where` query was found to be nearly impossible.

Remove `as any` from relations

---

docs/guide/relationships/getting-started.md

Describes relationship loading methods added in #94.

docs: loading all relationships

---

src/index.cjs.ts
src/index.ts

Adds missing module exports for `BelongsTo` and `MorphOne`.

fix: missing Attribute exports

---

src/plugin/Plugin.ts

Adds `BelongsTo`, `HasManyBy` and `MoprhOne` to plugin scope.

feat: add relations to plugin scope

---

src/index.cjs.ts

Export missing `MorphOne` decorator.

fix: export missing decorator

---

docs/guide/model/decorators.md
docs/guide/relationships/polymorphic.md

Adds `MorphTo` documentation, corrects some of the `MorphOne` documentation.
Blocked by #106

MorphTo Documentation
