- src/index.ts
- src/plugin/Plugin.ts
- src/store/Store.ts
- test/feature/plugin/plugin.spec.ts
> feat: add plugin feature

- src/repository/Repository.ts
- src/store/Store.ts
- src/support/Utils.ts
- src/types/vuex.ts
- test/feature/repository_custom/custom_repository.spec.ts
- test/unit/repository/Repository.spec.ts
Add custom repository support.
> feat: add custom repository support

- package.json
- src/helpers/Helpers.ts
- src/index.cjs.ts
- src/index.ts
- test/feature/helpers/helpers.spec.ts
Add `mapRepos` helper function.
> feat: add `mapRepos` helper

- docs/guide/prologue/getting-started.md
- docs/guide/prologue/installation.md
> docs: add getting started page

- docs/guide/prologue/what-is-vuex-orm.md
Update "What is Vuex ORM?" page.
> docs: update what is vuex orm page

- src/connection/Connection.ts
- src/modules/Mutations.ts
- src/query/Options.ts
- src/query/Query.ts
- src/repository/Repository.ts
- test/feature/repository/inserts_fresh.spec.ts
Add `fresh` method to the repository.
> feat: add "fresh" feature

- docs/.vuepress/config.js
- docs/guide/model/accessors.md
Add model accessors documentation.
> docs: add model accessors page

- docs/.vuepress/config.js
- docs/guide/digging-deeper/typescript.md
- docs/guide/model/getting-started.md
Add model getting started page.
> docs: add model getting started page

- docs/.vuepress/config.js
- docs/guide/repository/deleting-data.md
- docs/guide/repository/getting-started.md
- docs/guide/repository/inserting-data.md
- docs/guide/repository/retrieving-data.md
- docs/guide/repository/updating-data.md
Add repository getting started page.
> docs: add repository getting started page

- docs/guide/digging-deeper/plugins.md
> docs: add plugins page

- docs/guide/relationships/getting-started.md
- docs/guide/relationships/one-to-many.md
- docs/guide/relationships/one-to-one.md
Adds relationship pages to the docs.
> docs: add relationship pages

- docs/guide/repository/retrieving-data.md
Add repository retrieving data page to the docs.
> docs: add repository retriving data page

- docs/guide/repository/updating-data.md
Add repository updating data page.
> docs: add repository updating data page

- docs/guide/repository/deleting-data.md
Add repository deleting data page.
> docs: add repository deleting data page

- docs/guide/model/decorators.md
- docs/guide/relationships/one-to-many.md
- src/index.cjs.ts
- src/index.ts
- src/model/Model.ts
- src/model/attributes/relations/HasManyBy.ts
- src/model/decorators/attributes/relations/HasManyBy.ts
- test/feature/relations/has_many_by_insert.spec.ts
- test/feature/relations/has_many_by_insert_custom_key.spec.ts
- test/feature/relations/has_many_by_insert_uid.spec.ts
- test/feature/relations/has_many_by_retrieve.spec.ts
close #35 
This PR adds a new "has many by" relationship.
> feat: add has many by relation (#35)

- docs/guide/model/decorators.md
Fix the incorrect import in the @HasManyBy example of the decorator docs.
> fix import in @HasManyBy example

- src/model/Model.ts
- src/model/attributes/relations/BelongsTo.ts
- src/model/attributes/relations/HasMany.ts
- src/model/attributes/relations/HasManyBy.ts
- src/model/attributes/relations/HasOne.ts
- src/schema/Schema.ts
- test/feature/relations/nested/nested_relations.spec.ts
This PR fixes the nested relationship normalization error.
> fix: nested relations not getting normalized correctly

- src/connection/Connection.ts
- src/model/Model.ts
- test/unit/model/Model_Sanitize.spec.ts
This PR is for a https://github.com/vuex-orm/vuex-orm-next/pull/62.
This deal with a TODO to improve efficiency in the `src/connection/Connection.ts` below.
Instead of doing `$newInstance` and then `$getAttributes `, use the `$sanitize` or `$sanitizeAndFill` method of the Model.
```javascript
save(records: Elements): void {
this.commit('save', (data: Elements) => {
for (const id in records) {
const record = records[id]
const existing = data[id]
// TODO: Refactor this with more efficient methods.
existing
? Vue.set(
data,
id,
this.model
.$newInstance({ ...existing, ...record })
.$getAttributes()
)
: Vue.set(data, id, this.model.$newInstance(record).$getAttributes())
}
})
}
```
> feat: implement sanitize method in model

- src/index.cjs.ts
Export missing `HasManyBy` decorator.
> fix(decorator): export `HasManyBy` decorator

- src/interpreter/Interpreter.ts
> fix(interpreter): import database correctly (#74)

- docs/guide/relationships/one-to-many.md
fix issue https://github.com/vuex-orm/vuex-orm-next/issues/82
> fix docs for one-to-many(inverse) - 'userId' should be 'postId'

- README.md
i added an important info about typescript config as a config breaks `vuex-orm` (default on `vitejs` starter kit). i lost 2h trying to find what's wrong 😢 , hope this info could prevent others from loosing as much time as me.
> adding Important info to README.md

- docs/.vuepress/config.js
- docs/guide/model/decorators.md
- docs/guide/relationships/one-to-one-poly.md
- docs/guide/relationships/polymorphic.md
Adding documentation for Polymorphic One to One relations.
> Polymorphic One to One Documentation
